services:
  - type: web
    name: hrflow
    runtime: docker
    repo: https://github.com/anomalyco/Esprit-PIDEV-WEB--3A4-HrFlow
    branch: main
    dockerfilePath: ./Dockerfile
    dockerContext: ./
    port: 10000
    healthCheckPath: /
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: MESSENGER_TRANSPORT_DSN
        value: doctrine://default?auto_setup=0
      - key: MAILER_DSN
        sync: false
      - key: MAILER_FROM
        value: hr.flow28@gmail.com
      - key: MATRIX_CLIENT_URL
        value: https://matrix.org
      - key: MATRIX_ACCESS_TOKEN
        sync: false
      - key: MATRIX_BOT_USER_ID
        value: "@hrflow_matrix:matrix.org"
      - key: HUGGINGFACE_API_TOKEN
        sync: false
      - key: HUGGINGFACE_EMOTION_MODEL
        value: bhadresh-savani/distilbert-base-uncased-emotion
      - key: GEMINI_API_KEY
        sync: false
      - key: OPEN_ROUTER_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: NVIDIA_API_KEY
        sync: false
      - key: OPENWEATHER_API_KEY
        value: 8d45209a7b14cf087be60011ac99b6d6
      - key: NEWS_API_KEY
        value: 186a3494bd89f307704c95620c0204ca
      - key: CORS_ALLOW_ORIGINS
        value: https://esprit-pidev-web-3a4-hrflow-ctwx.onrender.com,https://www.hrflow.tech,https://hrflow.tech
      - key: APP_PUBLIC_URL
        sync: false
      - key: RECRUITMENT_EMAILS_ENABLED
        value: "false"
      - key: QUICKCHART_ENABLED
        value: "true"
      - key: UPLOAD_DIR
        value: /uploads/cv/
      - key: CHURN_API_URL
        value: http://127.0.0.1:8001/predict