# Google Gemini API Configuration
# Use environment variable GEMINI_API_KEY in production

gemini.api.key=AIzaSyA3NDzDEMN2_9zBDsdKvNVArRQlbfsu6gY

llm.provider=groq

groq.api.key=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
groq.api.model=llama-3.3-70b-versatile
groq.api.url=https://api.groq.com/openai/v1/chat/completions

# LLM Model Configuration
gemini.api.model=gemini-3-flash-preview
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-3-flash-preview:generateContent
