# Configuration de la base de données MySQL
db.url=jdbc:mysql://hrflow-hrflow.f.aivencloud.com:21031/defaultdb?ssl-mode=REQUIRED&useSSL=true&requireSSL=true
db.user=avnadmin
db.password=AVNS_7JkV8xT8CEbJDTKe9-4
db.driver=com.mysql.cj.jdbc.Driver
